config/routes.rb
Rails.application.routes.draw do


  devise_for :teachers
  devise_for :users


  root 'home#index'

  get 'cours/create'

  post 'cours/create' => 'cours#new'

  get 'cours/show'

  get 'cours/update'

  get 'cours/destroy'

  delete'cours/index' => 'cours#destroy'

  get 'cours/index'

  root 'cours#index'

  get 'cours' => 'cours#index'

  get 'cours/accueil'

  post 'cours/accueil' =>'cours#search'

  get 'cours/search'

  get 'cours/inscription'

  get 'cours/:id' => 'cours#show'

  get 'pages/monespace' 





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cour.rb
class Cour < ActiveRecord::Base

	geocoded_by :lieu, :params => {:countrycodes => "fr"}
	after_validation :geocode, if: ->(obj){ obj.lieu.present? and obj.lieu_changed? }
	has_many :users
	belongs_to :teacher
	#has_many :inscriptions

end

app/models/inscription.rb
class Inscription < ActiveRecord::Base
	#belongs_to :cour
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cours
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cours

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController

  before_action :authenticate_user! ,only: [:inscription]
  before_action :authenticate_teacher! ,only: [:new, :create, :destroy]

  def index
     @cours = Cour.page(params[:page]).per(20)
  end

  def create
  end

  def new
    cours = Cour.create teacher_id:current_teacher.id, matiere:params[:matiere], jour:params[:jour], 
    lieu:params[:lieu]
    #cours.latitude =  Geocoder.coordinates(params[:lieu])[0]
    #cours.longitude = Geocoder.coordinates(params[:lieu])[1]
    cours.save
    #sleep (3)
    redirect_to "/cours/index"
  end

  def show
    @cours = Cour.find(params[:id])
    @inscriptions = Inscription.where("cours_id=?",@cours.id)
  end

  def update
  end

  def destroy
    cours = Cour.find(params[:id]).destroy
    inscriptions = Inscription.where(cours_id: params[:id])
    inscriptions.each do |i|
      i.destroy
    end
    redirect_to '/cours/index'
  end

  def accueil
    @client_location = request.location.address
  end

  def search
    @cours = Cour.where("matiere=? AND nombre_eleves < ?", params[:matiere], 3)
    @lieu = params[:lieu]
    #@lieu_coo = Geocoder.coordinates(params[:lieu])

  end

  def inscription
    cours = Cour.find(params[:id])
    cours.nombre_eleves = cours.nombre_eleves + 1
    cours.save
    #cours.inscriptions.create eleves_id:current_user.id
    inscription = Inscription.create eleves_id:current_user.id, cours_id:cours.id
    inscription.save

    redirect_to '/cours/index'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to '/cours/index'
  	elsif teacher_signed_in?
  		redirect_to '/cours/index'
  	else
  		redirect_to new_user_session_path
  		
  	end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def monespace
  	#On affiche la liste des cours proposés si teacher et la liste des cours suivis si user
  	if user_signed_in?
  		@inscriptions = Inscription.where("eleves_id = ?", current_user.id)
  			
  	elsif teacher_signed_in?
  		@cours_proposes = Cour.where("teacher_id=?", current_teacher.id)
  	end
  		
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cours_helper.rb
module CoursHelper

	def index_link

		"<a href='/cours/index'> Revenir à l'index </a>".html_safe

	end 

end

app/helpers/homer_helper.rb
module HomerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cours/accueil.html.erb
<h1> Recherchez un cours </h1>

<p> <%= index_link %> </p>

<%=form_tag "/cours/accueil", method:"post" do %>
	<label for="matiere">Quelle matière souhaitez-vous travailler ?</label>
	<select name="matiere">
		<option value="mathematiques">Mathématiques</option>
		<option value="français">Français</option>
		<option value="anglais">Anglais</option>
		<option value="espagnol">Espagnol</option>
	</select>
	<label for="lieu">Indiquez votre adresse ?</label>
	<input type="text" name="lieu" size=40 value="<%=@client_location%>">
	<input type="submit" value="Envoyez">
<%end%>

app/views/cours/create.html.erb
<h1>Vous êtes enseignant, créez votre annonce simplement</h1>

<p><%=index_link%></p>



<%=form_tag "/cours/create", method:"post" do %>
	<fieldset>
		<legend> Détails du cours </legend>
		<p>
			<label for="professeur"> Quel est votre nom ? </label>
			<input type="text" name="professeur" required="indispensable">
		</p>
		<p>
			<label for="matiere"> Quelle matière souhaitez-vous enseigner?</label>
			<select name="matiere" required>
				<option value="mathematiques"> Mathématiques </option>
				<option value="francais"> Français </option>
				<option value="anglais"> Anglais </option>
				<option value="espagnol"> Espagnol </option>
			</select>>
		</p>
		<p>
			<label for="jour"> Quel jour seriez-vous disponible ? </label>
			<select name="jour" required="">
				<option>lundi</option>
				<option>mardi</option>
				<option>mercredi</option>
				<option>jeudi</option>
				<option>vendredi</option>
				<option>samedi</option>
				<option>dimanche</option>
			</select>
		</p>
		<p>
			<label for="lieu"> Indiquez l'adresse où le cours se tiendra</label>
			<input type="text" name="lieu" size=40 required>
		</p>
	</fieldset>
	<input type="submit" value="Envoyez">
<%end%>

app/views/cours/destroy.html.erb
<h1>Cours#destroy</h1>
<p>Find me in app/views/cours/destroy.html.erb</p>

app/views/cours/index.html.erb
<h1>Index des cours</h1>

<p> <a href="/cours/create"> Créez une annonce de cours </a> </p>
<p> <a href="/cours/accueil"> Cherchez un cours </a> </p>



<table>
	<tr>
		<th>Professeur</th>
		<th>Matière</th>
		<th>Disponibilité</th>
		<th>Nb eleves inscrits</th>
		<th>Lieu du cours</th>
		<th>Latitude</th>
		<th>Longitude</th>
	</tr>
	<% @cours.each do |cours| %>
	<tr>
		<td><%= Teacher.find(cours.teacher_id).email%></td>
		<td><%= cours.matiere %></td>
		<td><%= cours.jour %></td>
		<td><%= cours.nombre_eleves %></td>
		<td><%= cours.lieu %></td>
		<td><%= cours.latitude %></td>
		<td><%= cours.longitude %></td>
		<td><a href="/cours/<%=cours.id%>">Show</a></td>
		<td>
			<%= link_to "Destroy", {:controller => "cours", :action => "destroy", :id => cours.id }%>
		</td>
	</tr>
	<%end%>
</table>

</br>
<%= paginate @cours %>

app/views/cours/search.html.erb
<h1>Cours corrspondants à votre recherche</h1>


<p> <%= index_link %></p>

<p> Votre adresse : <%=@lieu%> </p>

<table>
	<tr>
		<th>Professeur</th>
		<th>Matière</th>
		<th>Disponibilité</th>
		<th>Nb eleves inscrits</th>
		<th>Adresse</th>
		<th>Distance</th>
	</tr>
	<% for cours in @cours.near(@lieu,20) %>
	<tr>
		<td><%= Teacher.find(cours.teacher_id).email%></td>
		<td><%= cours.matiere %></td>
		<td><%= cours.jour %></td>
		<td><%= cours.nombre_eleves %></td>
		<td><%= cours.lieu %></td>
		<td>
		<%= Geocoder::Calculations.distance_between([cours.latitude, cours.longitude], @lieu, :units =>:km) %>
		</td>
		<td><%= link_to "S'inscrire", {:controller =>"cours", :action=>"inscription", :id=>cours.id} %></td>
	</tr>
	<%end%>
</table>

app/views/cours/show.html.erb
<h1>Détails du cours proposé par <%= Teacher.find(@cours.teacher_id).email %> </h1>

<p> <%= index_link %> </p>

<p>
	<% @inscriptions.each do |i| %>
	Eleve inscrit : <%= User.find(i.eleves_id).email %>
	<br/>
	<%end%>
</p>

app/views/cours/update.html.erb
<h1>Cours#updaye</h1>
<p>Find me in app/views/cours/updaye.html.erb</p>

app/views/home/index.html.erb
<h1>Homer#index</h1>
<p>Find me in app/views/homer/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projet1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>

       <%= render partial:"shared/navbar"%>

       <% flash.each do |key, value| %>
       <% if key == "notice"
          key = "success"
        elsif key == "alert"
          key = "warning"
        end %>
            
        <div class="alert alert-<%= key %>">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <ul>
            <li>
              <%= value %>
            </li>
          </ul>
        </div>
      <% end %>



       <% if user_signed_in? %>
         <p>
         Bonjour user : <%= current_user.email %> 
         <%= link_to "Se déconnecter", destroy_user_session_path, :method => 'delete' %>
         </p>
       <% else %>
         <p>
         <%= link_to "Se connecter as user", new_user_session_path %>
         </p>
       <% end %>

       <% if teacher_signed_in? %>
         <p>
         Bonjour prof  : <%= current_teacher.email %> 
         <%= link_to "Se déconnecter", destroy_teacher_session_path, :method => 'delete' %>
         </p>
       <% else %>
         <p>
         <%= link_to "Se connecter as teacher", new_teacher_session_path %>
         </p>
       <% end %>

       <%= link_to "Espace Perso", {:controller => "/pages", :action => "monespace"}%>

       <!-- <p> <%= debug session.to_hash %> </p> -->
    <%= yield %>
  </body>
</html>

app/views/pages/_connexion.html.erb
<% if user_signed_in? %>
         <p>
         Bonjour : <%= current_user.email %> 
         <%= link_to "Se déconnecter", destroy_user_session_path, :method => 'delete' %>
         </p>
       <% else %>
         <p>
         <%= link_to "Se connecter as user", new_user_session_path %>
         </p>
       <% end %>

       <% if teacher_signed_in? %>
         <p>
         Bonjour : <%= current_teacher.email %> 
         <%= link_to "Se déconnecter", destroy_teacher_session_path, :method => 'delete' %>
         </p>
       <% else %>
         <p>
         <%= link_to "Se connecter as teacher", new_teacher_session_path %>
         </p>
       <% end %>

app/views/pages/monespace.html.erb
<h1>Pages#monespace</h1>

<% if user_signed_in? %>
	<%@inscriptions.each do |inscription| %>
		<p> cours du professeur : <%= Teacher.find(Cour.find(inscription.cours_id).teacher_id).email %> 
		<%= link_to " Détails du cours", {:controller =>"cours", :action => "show", :id => inscription.cours_id} %>
		</p>

	<% end %>
<% end %>

<% if teacher_signed_in? %>
	<%@cours_proposes.each do |cours| %>
		<p>
		<%= link_to "Cours Proposé", {:controller => "cours", :action => "show", :id => cours.id }%>
		</p>
	<% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
         <%= image_tag "logo_petit_rgb.png", alt:"Logo", width:"80", height:"30"%>
      </a>
    </div>
    <!-- Brand and toggle get grouped for better mobile display -->
    <!--
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>
    -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Inscrire et se connecter -->
        <% if user_signed_in? %>
            <li><a data-method="delete", href="/users/sign_out">Se déconnecter</a></li>
        <% elsif teacher_signed_in? %>
            <li><a data-method="delete", href="/teachers/sign_out">Se déconnecter</a></li>
        <% else %>
            <li class="active"><a href="/users/sign_up">S'inscrire <span class="sr-only">(current)</span></a></li>
            <li><a href="/users/sign_in">Se connecter</a></li>
        <% end %>
        <!-- Mon espace si connecté -->
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon espace <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/pages/monespace">Vos réservations</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% elsif teacher_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon espace <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/pages/monespace">Vos cours</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <!--
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <!-- Index pour admin et Proposer un cours -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/cours/index">Index</a></li>
        <li><a href="/cours/create">Proposer un cours</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/teachers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>